[package]
name = "samase_plugin"
version = "0.5.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
flate2 = "1.0.1"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
parking_lot = "0.11"
quick-error = "2.0"
thread_local = "1.0"
