[package]
name = "samase_shim"
version = "0.5.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
lazy_static = "1.0"
libc = "0.2"
parking_lot = "0.11"
thread_local = "1.0"
winapi = { version = "0.3", features = ["heapapi", "libloaderapi", "winuser"] }

[dependencies.samase_plugin]
path = ".."

[dependencies.whack]
git = "https://github.com/neivv/whack/"
rev = "e8e847864c2938735040ca3c68ef1cf9e03b692f"
