[package]
name = "samase_shim"
version = "0.5.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
lazy_static = "1.0"
libc = "0.2"
parking_lot = "0.9"
thread_local = "0.3.5"
winapi = { version = "0.3", features = ["heapapi", "libloaderapi", "winuser"] }

[dependencies.samase_plugin]
path = ".."

[dependencies.whack]
git = "https://github.com/neivv/whack/"
